version: '3.7'

services:
  wordpress:
    container_name: wp
    image: wordpress:latest
    ports:
      - '8000:80'
    volumes:
      - ./wp-data:/var/www/html
    entrypoint:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: yusuf
      WORDPRESS_DB_PASSWORD: yusuf_root
    networks:
      - wpsite

  phpmyadmin:
    container_name: wppypmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    entrypoint:
      PMA_HOST: db
      MYSQL_USER: yusuf1
      MYSQL_ROOT_PASSWORD: root
      
    networks:
      - wpsite
   db:
    image: mysql:5.7
    container_name: wpdb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yusuf
      MYSQL_PASSWORD: yusuf_root
      MYSQL_DATABASE: wp
    
    networks:
      - wpsite+
     
networks:
  wpsite:
volumes:
  db_data:

