version: '3'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_USER: yusuf
      WORDPRESS_DB_PASSWORD: yusuf_root
      WORDPRESS_DB_HOST: db:3306
      networks:
        - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: yusuf1
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: yusuf
      MYSQL_PASSWORD: yusuf_root
    networks:
      - wpsite+
networks:
  wpsite:
volumes:
  db_data:
